/**:
  ros__parameters:
    min_longitudinal_offset: 1.8
    max_longitudinal_offset: 5.0 #3.2[m] base_link2front
    min_lateral_offset: -1.4
    max_lateral_offset: 1.4
    min_height_offset: 0.8
    max_height_offset: 1.5
