/**:
  ros__parameters:
    wheel_radius: 0.39
    wheel_width: 0.21
    wheel_base: 3.8 # between front wheel center and rear wheel center
    wheel_tread: 1.7 # between left wheel center and right wheel center
    front_overhang: 1.18 # between front wheel center and vehicle front
    rear_overhang: 2.08 # between rear wheel center and vehicle rear
    left_overhang: 0.16 # between left wheel center and vehicle left
    right_overhang: 0.16 # between right wheel center and vehicle right
    vehicle_height: 2.7
    max_steer_angle: 0.70 # [rad]
